### ISSUE TITLE
ESMACS integration to RCT/EnTK

### ISSUE THREAD

**Issue by lee212** [inspiremd/Model-generation#7]

**Comment by lee212** [comment]
Initial code is here: https://github.com/2019-ncovgroup/DrugWorkflows/blob/devel/workflow-3/wf3.py
which is under the separated git repo but it describes ESMACS sim/analysis in EnTK.

**Comment by apbhati1** [comment]
Is it ready to use now?

**Comment by lee212** [comment]
At least for `raw_submission_esmacs.sh`, yes it is by `python wf3.py`. I will provide README for the brief instruction asap but I'd like to have a sanity check first to make sure it is ready to run. For example, I presumed that you have the executable `MMPBSA.py.MPI` which I can't find in the repo. I also see that 24 concurrent tasks are given with 24 nodes but wanted to confirm if each task consumes 40 cores.

**Comment by lee212** [comment]
FYI, I added a brief guide to run your scripts but using EnTK here:
https://github.com/2019-ncovgroup/DrugWorkflows/blob/devel/workflow-3/README.md

**Comment by apbhati1** [comment]
That's great. Thanks. I will soon upload the analysis codes for getting the final result after these two steps are successfully completed. But don't worry, that step is to be done locally and does not require any more work on your end :)

**Comment by apbhati1** [comment]
I have now added all the ESMACS analysis scripts required to get the final binding affinity value from the output of the two steps earlier. You need to execute `esmacs_analysis.py` on the login nodes or your local machine and it just takes a few seconds. README file contains brief instructions on its execution. Please give it a go and let me know if you're now able to run the entire workflow end to end.

**Comment by lee212** [comment]
@apbhati1, based on the discussion the slack channel, this integration is complete. I will get your code pushed to the git repo soon but can you confirm that this ticket is resolved and can be closed?

**Comment by apbhati1** [comment]
Yes. Sure. Thanks!
