### ISSUE TITLE
[ESMACS] syntax error: naming parameters, "3_traj" to "three_traj"?

### ISSUE THREAD

**Issue by lee212** [inspiremd/Model-generation#8]
https://github.com/inspiremd/Model-generation/blob/4252043261b8058b8666b1dac1e296614c8510db/impress_md/interface_functions.py#L269

**Comment by darkwhite29** [comment]
I confirm that it is also the case for me. The same syntax error.

**Comment by lee212** [comment]
@apbhati1 , can you comment?

**Comment by darkwhite29** [comment]
Summit now is down for maintenance. FYI. The support team claims it will take 4 hours to complete.

**Comment by apbhati1** [comment]
I never saw this error. I will check once Summit back online.

**Comment by darkwhite29** [comment]
I tested using both Python 2 and Python 3 before Summit is down. The same error for both, I believe.

**Comment by apbhati1** [comment]
Do you guys think that changing the parameter "3_traj" to "three_traj" or something which only contains string letters would solve the issue? It appears to me as a python issue!

**Comment by darkwhite29** [comment]
I think it is a Python issue as well, but since you do not have such errors. Let's wait and see when Summit is back.

**Comment by apbhati1** [comment]
Changing "3_traj" to "three_traj" solves the problem. I have committed the changes along with a few other small fixes. Please try now.

**Comment by lee212** [comment]
The commit: e426698abacae1b2bdf103a537e8c93570181514 fixes this
